[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# 增加函数超时时间
[functions."deepseek-proxy"]
  timeout = "30" # 设置为30秒

# 确保环境变量可用于函数
[context.production.environment]
  VITE_DEEPSEEK_API_KEY = "${VITE_DEEPSEEK_API_KEY}"

# 设置API代理
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 